import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ReduxProvider } from "@/redux/ReduxProvider";
import { AppProviders } from "@/reactQuery/ProviderQuery";
import AppProvider from "./_ui/wrapper/AppProvider";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //   const lang = typeof window !== "undefined" ? localStorage.getItem("i18nextLng") || "en" : "en"
  // const dir = lang === "ar" ? "rtl" : "ltr"
  return (
    <html >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
      
      <Suspense fallback={<>.... lo</>}>
        <AppProviders>
            <ReduxProvider>
                <AppProvider>
                        {children}
                
                </AppProvider>
            </ReduxProvider>
        </AppProviders>
       </Suspense>
      </body>
    </html>
  );
}
